# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodel', '0004_topic_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='add_date',
            field=models.DateTimeField(null=True),
        ),
    ]
