# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodel', '0005_auto_20170802_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='add_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
