# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodel', '0006_auto_20170802_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
