# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodel', '0007_topic_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='age',
        ),
        migrations.AddField(
            model_name='test',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
